# Use the official PostgreSQL image as a base
FROM postgres:16.4

# Copy initialization scripts
COPY ./postgres-init /docker-entrypoint-initdb.d

# (Optional) Expose the default PostgreSQL port
EXPOSE 5432