---
name: Go API

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: ["main"]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.4"

      - name: Check Go formatting
        run: |
          find . -name '*.go' -not -path "./vendor/*" -exec gofmt -l {} \; | tee /dev/stderr | (! read -r)

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run golangci-lint
        working-directory: golang-api
        run: golangci-lint run

      - name: Build Go
        working-directory: golang-api
        run: go build

      - name: Install godotenv
        run: go install github.com/joho/godotenv/cmd/godotenv@latest

      - name: Test API
        working-directory: golang-api
        run: godotenv -f .env.test go test ./...
