---
name: Lint YAML and Dockerfiles

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install yamllint
        run: |
          python -m pip install --upgrade pip
          pip install yamllint

      - name: Lint YAML files
        run: |
          yamllint **/*.yml

      - name: Install hadolint
        run: |
          wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.6.0/hadolint-Linux-x86_64
          chmod +x /bin/hadolint

      - name: Lint Dockerfiles
        run: |
          find . -type f -name '*Dockerfile*' -exec hadolint {} +
