---
name: Super Linter

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.4"
          
      - name: Build Go
        working-directory: golang-api
        run: go build

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          IGNORE_GITIGNORED_FILES: true
          FILTER_REGEX_EXCLUDE: ".*\\.env\\.test"