name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.4"

      - name: Install godotenv
        run: go install github.com/joho/godotenv/cmd/godotenv@latest

      - name: Test API
        working-directory: api
        run: godotenv -f .env.test go test ./...
